-- ════════════════════════════════════════════════════════════════════════════
-- Migration 19 — an API key's name is unique among ACTIVE keys, not forever
-- ════════════════════════════════════════════════════════════════════════════
--
-- Migration 18 created `ApiKey_businessId_name_key` as an UNCONDITIONAL unique
-- index on (businessId, name). That is the wrong scope, and it broke two things
-- that the Phase 3B.1 Prompt 3 release gate found by running them:
--
--   1. ROTATION WITH THE UNCHANGED NAME ALWAYS FAILED.
--
--      `rotateKey` revokes the predecessor and inserts the replacement in ONE
--      transaction, and the predecessor's row stays - that is the whole point of
--      the no-delete rule. With an unconditional index the replacement collided
--      with the row it was replacing, so the owner got
--      "That name is already in use".
--
--      The owner screen pre-fills the replacement name with the current name,
--      so this was not an edge case: pressing Replace and then Replace it - the
--      default path, and the action `docs/PUBLIC-API-V1.md` tells a consumer to
--      take when they suspect a key - failed every time.
--
--   2. A NAME WAS BURNED FOREVER.
--
--      Revoke "Reporting" and no key could ever be called "Reporting" again.
--      Keys expire after ninety days, so a business that rotates on schedule
--      accumulates dead names indefinitely and eventually has to invent
--      "Reporting 4" to describe the same thing.
--
-- WHAT UNIQUENESS IS ACTUALLY FOR HERE. The name is the owner's own label, and
-- it exists so they can tell their LIVE keys apart in a list. Two revoked keys
-- sharing a name confuses nobody: the list shows the state and the dates, and
-- every audit row references a key by id rather than by name. So the constraint
-- belongs on the active set.
--
-- WHY THIS IS SAFE ON AN ENVIRONMENT WHERE MIGRATION 18 IS ALREADY APPLIED.
-- The new index is STRICTLY WEAKER than the one it replaces: unconditional
-- uniqueness over all rows implies uniqueness over the ACTIVE subset. Any data
-- that satisfied the old index satisfies the new one, so the CREATE cannot fail
-- on existing rows, in any environment, whatever it holds. Nothing is deleted,
-- nothing is rewritten, and no row changes.
--
-- WHY THIS IS AN INDEX AND NOT A TRIGGER. The same reason the active-slot
-- ceiling is an index: a trigger that SELECTs cannot exclude a concurrent
-- transaction, because a BEFORE INSERT trigger sees only committed rows, so two
-- simultaneous creations would each find no clash and both insert. A partial
-- unique index IS serialized by PostgreSQL - the second inserter blocks on the
-- first's uncommitted entry and is refused when it commits.
--
-- ── ORDER OF THE TWO STATEMENTS ─────────────────────────────────────────────
--
-- CREATE FIRST, DROP SECOND. An earlier draft did the reverse, which put the
-- most restrictive lock in front of the longest operation - exactly backwards.
--
--   CREATE UNIQUE INDEX   takes SHARE on "ApiKey". Blocks writers; reads are
--                         served. This is the statement whose cost grows with
--                         the size of the table, and it now runs while the
--                         authentication LOOKUP can still complete. See the
--                         section below for why that is not the same as saying
--                         an API request is served.
--
--   DROP INDEX            takes ACCESS EXCLUSIVE - blocks readers and writers
--                         alike - but it is a catalog operation on an index
--                         that already exists, and it runs LAST, after the
--                         replacement is built and valid.
--
-- Locks are held until the transaction commits, so from the DROP onwards the
-- table is unavailable to everybody for the remainder of the transaction. That
-- remainder is one catalog update rather than an index build, which is the
-- whole point of this ordering.
--
-- UNIQUENESS IS NEVER ABSENT, not even momentarily. During the CREATE the old
-- unconditional index still exists and still enforces a STRICTER rule; once the
-- new index is valid both are enforcing; the DROP then removes the stricter one.
-- Prisma runs a migration file in a single transaction, so there is no committed
-- state in which neither index constrains an ACTIVE name. A failure at any point
-- rolls the whole thing back to migration 18's arrangement.
--
-- ── WHY NOT CONCURRENTLY ────────────────────────────────────────────────────
--
-- `CREATE INDEX CONCURRENTLY` and `DROP INDEX CONCURRENTLY` cannot run inside a
-- transaction block, and Prisma executes a migration file inside one. Using them
-- would mean abandoning that transaction, and with it the guarantee above: there
-- would be committed intermediate states, and a consumer or an operator could
-- observe the table with only one of the two indexes - or, if a CONCURRENTLY
-- build failed, with an INVALID index left behind that enforces nothing and must
-- be dropped by hand before a retry.
--
-- Atomicity is worth more here than availability, because the alternative
-- failure mode is a half-migrated production database that silently stops
-- constraining live key names. The cost of that choice is stated below rather
-- than hidden.
--
-- ── OPERATIONAL COST, STATED HONESTLY ───────────────────────────────────────
--
-- **NO DURATION IS CLAIMED.** An earlier draft said the build takes
-- milliseconds because a business holds at most five active keys. That reasoning
-- was wrong: the five-key ceiling bounds ACTIVE rows only, and retired
-- predecessors are never deleted - `ApiKey` has no retention or deletion policy
-- at all, which is the open owner decision D31. Keys expire every ninety days,
-- so the table grows without bound for as long as the product is used, and the
-- index build scales with the total row count rather than with the active one.
--
-- What is actually true, stated per request rather than per statement - because
-- "the lookup is a read" is NOT the same claim as "the request is served", and
-- an earlier draft of this comment ran the two together:
--
--   DURING THE CREATE (SHARE: writes wait, reads do not)
--
--     * The authentication LOOKUP completes. `authenticateApiKey` is a single
--       indexed SELECT on the digest, and SHARE does not block it.
--     * A REQUEST THAT IS ABOUT TO BE SERVED THEN WAITS. `guardApiRequest`
--       awaits `touchKey()` before the handler runs, and that is an UPDATE of
--       `lastUsedAt` on this table - so a successful `/api/v1` read blocks until
--       this migration commits. The lookup succeeding does not mean the caller
--       gets an answer.
--     * A REQUEST THAT IS REFUSED STILL COMPLETES, because every refusal returns
--       before `touchKey` is reached: a missing or bad key (401), a wrong scope
--       (403), a credential in the query string (400), and a rate-limited caller
--       (429 - its counter is in `AuthRateLimit`, a different table).
--     * OWNER KEY MUTATIONS WAIT. Create, rotate and revoke are writes here.
--
--   FROM THE DROP TO THE COMMIT (ACCESS EXCLUSIVE: everything waits)
--
--     * Reads wait too, INCLUDING THE AUTHENTICATION LOOKUP ITSELF. For this
--       span no `/api/v1` request can even be authenticated.
--     * That span is one catalog operation rather than an index build, which is
--       the entire reason the CREATE goes first.
--
--   Nothing else in the product touches this table, so no other feature is
--   affected in either window.
--
-- **DEPLOY THIS IN A CONTROLLED LOW-TRAFFIC WINDOW.** Not because a duration is
-- known, but because it is not: the only honest planning assumption is that the
-- build time is proportional to a table whose size nobody has bounded, and that
-- for that whole time an authenticated public-API request may be waiting rather
-- than being answered. Check `SELECT count(*) FROM "ApiKey"` beforehand if a
-- window needs sizing.

CREATE UNIQUE INDEX "ApiKey_businessId_activeName_key"
  ON "ApiKey"("businessId", "name")
  WHERE "state" = 'ACTIVE';

DROP INDEX "ApiKey_businessId_name_key";
