import { OperationSource } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import { ValidationError } from "@/server/errors";
import { errorResponse, readJsonObject } from "@/server/http";
import { awardManualStamps, awardPurchaseStamps, awardVisitStamp } from "@/server/stamp/engine";
import { enforceStaffLimit } from "@/server/security/staff-limit";
import { requireScannerContext } from "@/server/tenant/scanner-context";

/**
 * POST /api/scanner/award — give stamps.
 *
 * The route chooses which engine verb to call and does nothing else. It builds no ledger rows and
 * touches no balance.
 *
 * **The body is now parsed strictly** (Phase 1b Prompt 2). It used to be read field by field with
 * `String(body.x ?? "")`, which accepted anything and coerced it: a missing `customerCardId` became
 * the empty string and travelled to the engine as a lookup that could only fail, and an unknown
 * field was silently dropped. A discriminated union refuses the body instead, and names the field.
 *
 * `locationId` is accepted here and nowhere public. It means something only when the card's pinned
 * version lists `availableLocations`; a Phase 1a version refuses it with the same message it always
 * has, and the engine checks the program's list AND this member's own assignment inside the write
 * transaction. The nested-location guard still applies to every other key.
 *
 * `idempotencyKey` is generated by the client and honoured by the server, because this endpoint is
 * fired by a person tapping a phone at a counter on a bad network. The same key replays the same
 * answer; a different intent under the same key is refused rather than silently applied.
 */

const base = {
  businessId: z.string().min(1).optional(),
  customerCardId: z.string().min(1),
  idempotencyKey: z.string().min(8),
  locationId: z.string().min(1).optional(),
  comment: z.string().trim().max(500).optional(),
};

const bodySchema = z.discriminatedUnion("mode", [
  z.strictObject({ ...base, mode: z.literal("manual"), quantity: z.number().int().min(1), purchaseAmountMinor: z.number().int().min(0).optional() }),
  z.strictObject({ ...base, mode: z.literal("visit"), purchaseAmountMinor: z.number().int().min(0).optional() }),
  z.strictObject({ ...base, mode: z.literal("purchase"), purchaseAmountMinor: z.number().int().min(0) }),
]);

export async function POST(req: Request) {
  try {
    const parsed = bodySchema.safeParse(await readJsonObject(req, { allowLocation: true }));
    if (!parsed.success) throw new ValidationError("Invalid award", parsed.error.issues);
    const input = parsed.data;

    const { ctx } = await requireScannerContext(input.businessId ?? null);
    // Finding M-11: one member of staff, one window. Counted after the membership is verified
    // (there is nothing to key on before that) and before the service runs.
    await enforceStaffLimit(ctx, "write");
    const common = {
      customerCardId: input.customerCardId,
      idempotencyKey: input.idempotencyKey,
      source: OperationSource.SCANNER,
      locationId: input.locationId,
      comment: input.comment?.trim() || undefined,
    };

    switch (input.mode) {
      case "manual":
        return NextResponse.json(
          await awardManualStamps(ctx, { ...common, quantity: input.quantity, purchaseAmountMinor: input.purchaseAmountMinor }),
        );
      case "visit":
        return NextResponse.json(await awardVisitStamp(ctx, { ...common, purchaseAmountMinor: input.purchaseAmountMinor }));
      case "purchase":
        return NextResponse.json(await awardPurchaseStamps(ctx, { ...common, purchaseAmountMinor: input.purchaseAmountMinor }));
    }
  } catch (e) {
    return errorResponse(e);
  }
}
