import { OperationSource } from "@prisma/client";
import { NextResponse } from "next/server";
import { ValidationError } from "@/server/errors";
import { errorResponse, readJsonObject } from "@/server/http";
import { awardManualStamps, awardPurchaseStamps, awardVisitStamp } from "@/server/stamp/engine";
import { requireScannerContext } from "@/server/tenant/scanner-context";

/**
 * POST /api/scanner/award — give stamps.
 *
 * The route chooses which engine verb to call and does nothing else. It builds no ledger rows,
 * touches no balance, and names no location: the engine resolves `Main` itself, and
 * `readJsonObject` has already refused a body that tried to name one.
 *
 * `idempotencyKey` is generated by the client and honoured by the server, because this endpoint is
 * fired by a person tapping a phone at a counter on a bad network. The same key replays the same
 * answer; a different intent under the same key is refused rather than silently applied.
 */
export async function POST(req: Request) {
  try {
    const body = await readJsonObject(req);
    const { ctx } = await requireScannerContext(typeof body.businessId === "string" ? body.businessId : null);

    const customerCardId = String(body.customerCardId ?? "");
    const idempotencyKey = String(body.idempotencyKey ?? "");
    const comment = typeof body.comment === "string" && body.comment.trim() !== "" ? body.comment.trim() : undefined;
    const common = { customerCardId, idempotencyKey, source: OperationSource.SCANNER, comment };

    switch (body.mode) {
      case "manual": {
        if (typeof body.quantity !== "number") throw new ValidationError("quantity is required for a manual award");
        return NextResponse.json(
          await awardManualStamps(ctx, {
            ...common,
            quantity: body.quantity,
            purchaseAmountMinor: typeof body.purchaseAmountMinor === "number" ? body.purchaseAmountMinor : undefined,
          }),
        );
      }
      case "visit":
        return NextResponse.json(
          await awardVisitStamp(ctx, {
            ...common,
            purchaseAmountMinor: typeof body.purchaseAmountMinor === "number" ? body.purchaseAmountMinor : undefined,
          }),
        );
      case "purchase": {
        if (typeof body.purchaseAmountMinor !== "number") {
          throw new ValidationError("purchaseAmountMinor is required for a purchase award");
        }
        return NextResponse.json(await awardPurchaseStamps(ctx, { ...common, purchaseAmountMinor: body.purchaseAmountMinor }));
      }
      default:
        throw new ValidationError("mode must be manual, visit or purchase");
    }
  } catch (e) {
    return errorResponse(e);
  }
}
